### ISSUE TITLE
Add CI and such

### ISSUE THREAD

**Issue by duckinator** [duckinator/rgdev#4]
Basically: use Cirrus CI's [Docker Builder VM tasks](https://cirrus-ci.org/guide/docker-builder-vm/) to build the image, then use that image with something along the lines of:

```
test_task:
  container:
    dockerfile: Dockerfile
  script:
    - git clone https://github.com/rubygems/rubygems.git
    # TODO: Update this to actually work, I guess, since the whole reason I opened this issue is because this fails locally.
    - rake setup
    - rake test
```
